# Site settings
title: Stanford Computational Journalism Lab
email: journalism@commu.stanford.edu
description: Computational methods in the pursuit of accountability journalism and data-driven storytelling.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cjlab.stanford.edu" # the base hostname & protocol for your site
twitter_username: stanfordjourn
github_username:  stanfordjourn

github_repo: compjolab/cjlab-homepage


service_ids:
  google_analytics: "UA-68150677-1"
  google_search: '012541043402465721355:csszj3j0mao'

# Build settings
markdown: kramdown

permalink: pretty
sass:
    sass_dir: assets/_sass


collections:
  projects:
    output: true
    permalink: /projects/:path/
    layout: page

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      type: "projects"
    values:
      layout: "page"

gems:
  - octopress-autoprefixer
  - s3_website
  - jekyll-assets
  - uglifier
  - jekyll-sitemap

assets:
  js_compressor:  uglifier
  css_compressor: sass
  gzip: [ text/css, application/javascript ]
  cachebust: hard
  debug: false
