# Site settings
title: Stanford Computational Journalism Lab
email: journalism@commu.stanford.edu
description: Data-driven storytelling from Silicon Valley

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stanfordcompjolabsite.s3-website-us-east-1.amazonaws.com" # the base hostname & protocol for your site
twitter_username: stanfordjourn
github_username:  stanfordjourn

github_repo: compjolab/compjolab.github.io


# Build settings
markdown: kramdown

permalink: pretty
sass:
    sass_dir: assets/_sass


collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      type: "pages"
    values:
      layout: "page"
  - scope:
      type: "projects"
    values:
      layout: "page"

gems:
  - octopress-autoprefixer
  - s3_website
