# Site settings
title: Stanford Computational Journalism Lab
email: your-emailTKTK@domain.com
description: |
  Data-driven curriculum for the journalist of tomorrow
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://compjolab.github.io" # the base hostname & protocol for your site
twitter_username: stanfordjourn
github_username:  stanfordjourn

# Build settings
markdown: kramdown

permalink: pretty
sass:
    sass_dir: assets/_sass



defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      type: "pages"
    values:
      layout: "page"

